version: "3.9"
services:
 mono:
  image: mono:latest
  container_name: mono_1
  ports:
   - "8080:8080"
  volumes:
   - /Users/sandrakumi/Library/CloudStorage/OneDrive-UniversityofSaskatchewan/PhD_Courses/CMPT_436/Tutorials/JavaClient_MonoServer:/code
  stdin_open: true
  tty: true
 java:
  image: openjdk:latest
  container_name: java_1
  ports:
   - "8081:80"
  command: ["bin/bash"]
  volumes:
   - /Users/sandrakumi/Library/CloudStorage/OneDrive-UniversityofSaskatchewan/PhD_Courses/CMPT_436/Tutorials/JavaClient_MonoServer:/code
  stdin_open: true
  tty: true
  
